[package]
name = "nkl"
version = "0.0.2"
edition = "2021"
authors = ["Loky HARK"]
description = "Nuclear Kernel Library"
license = "MIT"
repository = "https://github.com/nkl-org/nkl"
keywords = ["nuclear"]
categories = ["science"]
