/// Periodic table chemical element.
///
/// # Examples
///
/// ```
/// # use nkl::core::Element;
/// let hydrogen = Element::Hydrogen;
/// let name = hydrogen.name();
/// let symbol = hydrogen.symbol();
/// let atomic_number = hydrogen.atomic_number();
/// ```
///
/// # Notes
///
/// - Chemical element from *Hydrogen* (Z = 1) to *Oganesson* (Z = 118) are included.
/// - `Element` enum is marked as non exhaustive for future-proofing.
#[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
#[non_exhaustive]
#[allow(missing_docs)]
pub enum Element {
    Hydrogen,
    Helium,
    Lithium,
    Beryllium,
    Boron,
    Carbon,
    Nitrogen,
    Oxygen,
    Fluorine,
    Neon,
    Sodium,
    Magnesium,
    Aluminium,
    Silicon,
    Phosphorus,
    Sulfur,
    Chlorine,
    Argon,
    Potassium,
    Calcium,
    Scandium,
    Titanium,
    Vanadium,
    Chromium,
    Manganese,
    Iron,
    Cobalt,
    Nickel,
    Copper,
    Zinc,
    Gallium,
    Germanium,
    Arsenic,
    Selenium,
    Bromine,
    Krypton,
    Rubidium,
    Strontium,
    Yttrium,
    Zirconium,
    Niobium,
    Molybdenum,
    Technetium,
    Ruthenium,
    Rhodium,
    Palladium,
    Silver,
    Cadmium,
    Indium,
    Tin,
    Antimony,
    Tellurium,
    Iodine,
    Xenon,
    Caesium,
    Barium,
    Lanthanum,
    Cerium,
    Praseodymium,
    Neodymium,
    Promethium,
    Samarium,
    Europium,
    Gadolinium,
    Terbium,
    Dysprosium,
    Holmium,
    Erbium,
    Thulium,
    Ytterbium,
    Lutetium,
    Hafnium,
    Tantalum,
    Tungsten,
    Rhenium,
    Osmium,
    Iridium,
    Platinum,
    Gold,
    Mercury,
    Thallium,
    Lead,
    Bismuth,
    Polonium,
    Astatine,
    Radon,
    Francium,
    Radium,
    Actinium,
    Thorium,
    Protactinium,
    Uranium,
    Neptunium,
    Plutonium,
    Americium,
    Curium,
    Berkelium,
    Californium,
    Einsteinium,
    Fermium,
    Mendelevium,
    Nobelium,
    Lawrencium,
    Rutherfordium,
    Dubnium,
    Seaborgium,
    Bohrium,
    Hassium,
    Meitnerium,
    Darmstadtium,
    Roentgenium,
    Copernicium,
    Nihonium,
    Flerovium,
    Moscovium,
    Livermorium,
    Tennessine,
    Oganesson,
}

impl Element {
    /// Returns `Element` corresponding to specified `name` (case insensitive).
    ///
    /// # Returns
    ///
    /// - `Some(element)` if `name` is a standard element name (case insensitive)
    /// - `None` if `name` is **not** a standard element name
    ///
    /// # Examples
    ///
    /// ```
    /// # use nkl::core::Element;
    /// let hydrogen = Element::from_name("Hydrogen");
    /// ```
    pub fn from_name(name: &str) -> Option<Self> {
        match name.to_ascii_lowercase().as_str() {
            "hydrogen" => Some(Element::Hydrogen),
            "helium" => Some(Element::Helium),
            "lithium" => Some(Element::Lithium),
            "beryllium" => Some(Element::Beryllium),
            "boron" => Some(Element::Boron),
            "carbon" => Some(Element::Carbon),
            "nitrogen" => Some(Element::Nitrogen),
            "oxygen" => Some(Element::Oxygen),
            "fluorine" => Some(Element::Fluorine),
            "neon" => Some(Element::Neon),
            "sodium" => Some(Element::Sodium),
            "magnesium" => Some(Element::Magnesium),
            "aluminium" => Some(Element::Aluminium),
            "silicon" => Some(Element::Silicon),
            "phosphorus" => Some(Element::Phosphorus),
            "sulfur" => Some(Element::Sulfur),
            "chlorine" => Some(Element::Chlorine),
            "argon" => Some(Element::Argon),
            "potassium" => Some(Element::Potassium),
            "calcium" => Some(Element::Calcium),
            "scandium" => Some(Element::Scandium),
            "titanium" => Some(Element::Titanium),
            "vanadium" => Some(Element::Vanadium),
            "chromium" => Some(Element::Chromium),
            "manganese" => Some(Element::Manganese),
            "iron" => Some(Element::Iron),
            "cobalt" => Some(Element::Cobalt),
            "nickel" => Some(Element::Nickel),
            "copper" => Some(Element::Copper),
            "zinc" => Some(Element::Zinc),
            "gallium" => Some(Element::Gallium),
            "germanium" => Some(Element::Germanium),
            "arsenic" => Some(Element::Arsenic),
            "selenium" => Some(Element::Selenium),
            "bromine" => Some(Element::Bromine),
            "krypton" => Some(Element::Krypton),
            "rubidium" => Some(Element::Rubidium),
            "strontium" => Some(Element::Strontium),
            "yttrium" => Some(Element::Yttrium),
            "zirconium" => Some(Element::Zirconium),
            "niobium" => Some(Element::Niobium),
            "molybdenum" => Some(Element::Molybdenum),
            "technetium" => Some(Element::Technetium),
            "ruthenium" => Some(Element::Ruthenium),
            "rhodium" => Some(Element::Rhodium),
            "palladium" => Some(Element::Palladium),
            "silver" => Some(Element::Silver),
            "cadmium" => Some(Element::Cadmium),
            "indium" => Some(Element::Indium),
            "tin" => Some(Element::Tin),
            "antimony" => Some(Element::Antimony),
            "tellurium" => Some(Element::Tellurium),
            "iodine" => Some(Element::Iodine),
            "xenon" => Some(Element::Xenon),
            "caesium" => Some(Element::Caesium),
            "barium" => Some(Element::Barium),
            "lanthanum" => Some(Element::Lanthanum),
            "cerium" => Some(Element::Cerium),
            "praseodymium" => Some(Element::Praseodymium),
            "neodymium" => Some(Element::Neodymium),
            "promethium" => Some(Element::Promethium),
            "samarium" => Some(Element::Samarium),
            "europium" => Some(Element::Europium),
            "gadolinium" => Some(Element::Gadolinium),
            "terbium" => Some(Element::Terbium),
            "dysprosium" => Some(Element::Dysprosium),
            "holmium" => Some(Element::Holmium),
            "erbium" => Some(Element::Erbium),
            "thulium" => Some(Element::Thulium),
            "ytterbium" => Some(Element::Ytterbium),
            "lutetium" => Some(Element::Lutetium),
            "hafnium" => Some(Element::Hafnium),
            "tantalum" => Some(Element::Tantalum),
            "tungsten" => Some(Element::Tungsten),
            "rhenium" => Some(Element::Rhenium),
            "osmium" => Some(Element::Osmium),
            "iridium" => Some(Element::Iridium),
            "platinum" => Some(Element::Platinum),
            "gold" => Some(Element::Gold),
            "mercury" => Some(Element::Mercury),
            "thallium" => Some(Element::Thallium),
            "lead" => Some(Element::Lead),
            "bismuth" => Some(Element::Bismuth),
            "polonium" => Some(Element::Polonium),
            "astatine" => Some(Element::Astatine),
            "radon" => Some(Element::Radon),
            "francium" => Some(Element::Francium),
            "radium" => Some(Element::Radium),
            "actinium" => Some(Element::Actinium),
            "thorium" => Some(Element::Thorium),
            "protactinium" => Some(Element::Protactinium),
            "uranium" => Some(Element::Uranium),
            "neptunium" => Some(Element::Neptunium),
            "plutonium" => Some(Element::Plutonium),
            "americium" => Some(Element::Americium),
            "curium" => Some(Element::Curium),
            "berkelium" => Some(Element::Berkelium),
            "californium" => Some(Element::Californium),
            "einsteinium" => Some(Element::Einsteinium),
            "fermium" => Some(Element::Fermium),
            "mendelevium" => Some(Element::Mendelevium),
            "nobelium" => Some(Element::Nobelium),
            "lawrencium" => Some(Element::Lawrencium),
            "rutherfordium" => Some(Element::Rutherfordium),
            "dubnium" => Some(Element::Dubnium),
            "seaborgium" => Some(Element::Seaborgium),
            "bohrium" => Some(Element::Bohrium),
            "hassium" => Some(Element::Hassium),
            "meitnerium" => Some(Element::Meitnerium),
            "darmstadtium" => Some(Element::Darmstadtium),
            "roentgenium" => Some(Element::Roentgenium),
            "copernicium" => Some(Element::Copernicium),
            "nihonium" => Some(Element::Nihonium),
            "flerovium" => Some(Element::Flerovium),
            "moscovium" => Some(Element::Moscovium),
            "livermorium" => Some(Element::Livermorium),
            "tennessine" => Some(Element::Tennessine),
            "oganesson" => Some(Element::Oganesson),
            _ => None,
        }
    }

    /// Returns `Element` corresponding to specified symbol.
    ///
    /// # Returns
    ///
    /// - `Some(element)` if `symbol` is a standard element symbol (case insensitive)
    /// - `None` if `symbol` is **not** a standard element symbol
    ///
    /// # Examples
    ///
    /// ```
    /// # use nkl::core::Element;
    /// let hydrogen = Element::from_symbol("H");
    /// ```
    pub fn from_symbol(symbol: &str) -> Option<Self> {
        match symbol.to_ascii_lowercase().as_str() {
            "h" => Some(Element::Hydrogen),
            "he" => Some(Element::Helium),
            "li" => Some(Element::Lithium),
            "be" => Some(Element::Beryllium),
            "b" => Some(Element::Boron),
            "c" => Some(Element::Carbon),
            "n" => Some(Element::Nitrogen),
            "o" => Some(Element::Oxygen),
            "f" => Some(Element::Fluorine),
            "ne" => Some(Element::Neon),
            "na" => Some(Element::Sodium),
            "mg" => Some(Element::Magnesium),
            "al" => Some(Element::Aluminium),
            "si" => Some(Element::Silicon),
            "p" => Some(Element::Phosphorus),
            "s" => Some(Element::Sulfur),
            "cl" => Some(Element::Chlorine),
            "ar" => Some(Element::Argon),
            "k" => Some(Element::Potassium),
            "ca" => Some(Element::Calcium),
            "sc" => Some(Element::Scandium),
            "ti" => Some(Element::Titanium),
            "v" => Some(Element::Vanadium),
            "cr" => Some(Element::Chromium),
            "mn" => Some(Element::Manganese),
            "fe" => Some(Element::Iron),
            "co" => Some(Element::Cobalt),
            "ni" => Some(Element::Nickel),
            "cu" => Some(Element::Copper),
            "zn" => Some(Element::Zinc),
            "ga" => Some(Element::Gallium),
            "ge" => Some(Element::Germanium),
            "as" => Some(Element::Arsenic),
            "se" => Some(Element::Selenium),
            "br" => Some(Element::Bromine),
            "kr" => Some(Element::Krypton),
            "rb" => Some(Element::Rubidium),
            "sr" => Some(Element::Strontium),
            "y" => Some(Element::Yttrium),
            "zr" => Some(Element::Zirconium),
            "nb" => Some(Element::Niobium),
            "mo" => Some(Element::Molybdenum),
            "tc" => Some(Element::Technetium),
            "ru" => Some(Element::Ruthenium),
            "rh" => Some(Element::Rhodium),
            "pd" => Some(Element::Palladium),
            "ag" => Some(Element::Silver),
            "cd" => Some(Element::Cadmium),
            "in" => Some(Element::Indium),
            "sn" => Some(Element::Tin),
            "sb" => Some(Element::Antimony),
            "te" => Some(Element::Tellurium),
            "i" => Some(Element::Iodine),
            "xe" => Some(Element::Xenon),
            "cs" => Some(Element::Caesium),
            "ba" => Some(Element::Barium),
            "la" => Some(Element::Lanthanum),
            "ce" => Some(Element::Cerium),
            "pr" => Some(Element::Praseodymium),
            "nd" => Some(Element::Neodymium),
            "pm" => Some(Element::Promethium),
            "sm" => Some(Element::Samarium),
            "eu" => Some(Element::Europium),
            "gd" => Some(Element::Gadolinium),
            "tb" => Some(Element::Terbium),
            "dy" => Some(Element::Dysprosium),
            "ho" => Some(Element::Holmium),
            "er" => Some(Element::Erbium),
            "tm" => Some(Element::Thulium),
            "yb" => Some(Element::Ytterbium),
            "lu" => Some(Element::Lutetium),
            "hf" => Some(Element::Hafnium),
            "ta" => Some(Element::Tantalum),
            "w" => Some(Element::Tungsten),
            "re" => Some(Element::Rhenium),
            "os" => Some(Element::Osmium),
            "ir" => Some(Element::Iridium),
            "pt" => Some(Element::Platinum),
            "au" => Some(Element::Gold),
            "hg" => Some(Element::Mercury),
            "tl" => Some(Element::Thallium),
            "pb" => Some(Element::Lead),
            "bi" => Some(Element::Bismuth),
            "po" => Some(Element::Polonium),
            "at" => Some(Element::Astatine),
            "rn" => Some(Element::Radon),
            "fr" => Some(Element::Francium),
            "ra" => Some(Element::Radium),
            "ac" => Some(Element::Actinium),
            "th" => Some(Element::Thorium),
            "pa" => Some(Element::Protactinium),
            "u" => Some(Element::Uranium),
            "np" => Some(Element::Neptunium),
            "pu" => Some(Element::Plutonium),
            "am" => Some(Element::Americium),
            "cm" => Some(Element::Curium),
            "bk" => Some(Element::Berkelium),
            "cf" => Some(Element::Californium),
            "es" => Some(Element::Einsteinium),
            "fm" => Some(Element::Fermium),
            "md" => Some(Element::Mendelevium),
            "no" => Some(Element::Nobelium),
            "lr" => Some(Element::Lawrencium),
            "rf" => Some(Element::Rutherfordium),
            "db" => Some(Element::Dubnium),
            "sg" => Some(Element::Seaborgium),
            "bh" => Some(Element::Bohrium),
            "hs" => Some(Element::Hassium),
            "mt" => Some(Element::Meitnerium),
            "ds" => Some(Element::Darmstadtium),
            "rg" => Some(Element::Roentgenium),
            "cn" => Some(Element::Copernicium),
            "nh" => Some(Element::Nihonium),
            "fl" => Some(Element::Flerovium),
            "mc" => Some(Element::Moscovium),
            "lv" => Some(Element::Livermorium),
            "ts" => Some(Element::Tennessine),
            "og" => Some(Element::Oganesson),
            _ => None,
        }
    }

    /// Returns `Element` corresponding to specified atomic number.
    ///
    /// # Returns
    ///
    /// - `Some(element)` if `atomic_number` ∈ `[1, 118]`
    /// - `None` if `atomic_number` ∉ `[0, 118]`
    ///
    /// # Examples
    ///
    /// ```
    /// # use nkl::core::Element;
    /// let hydrogen = Element::from_atomic_number(1);
    /// ```
    pub fn from_atomic_number(atomic_number: u32) -> Option<Self> {
        match atomic_number {
            1 => Some(Element::Hydrogen),
            2 => Some(Element::Helium),
            3 => Some(Element::Lithium),
            4 => Some(Element::Beryllium),
            5 => Some(Element::Boron),
            6 => Some(Element::Carbon),
            7 => Some(Element::Nitrogen),
            8 => Some(Element::Oxygen),
            9 => Some(Element::Fluorine),
            10 => Some(Element::Neon),
            11 => Some(Element::Sodium),
            12 => Some(Element::Magnesium),
            13 => Some(Element::Aluminium),
            14 => Some(Element::Silicon),
            15 => Some(Element::Phosphorus),
            16 => Some(Element::Sulfur),
            17 => Some(Element::Chlorine),
            18 => Some(Element::Argon),
            19 => Some(Element::Potassium),
            20 => Some(Element::Calcium),
            21 => Some(Element::Scandium),
            22 => Some(Element::Titanium),
            23 => Some(Element::Vanadium),
            24 => Some(Element::Chromium),
            25 => Some(Element::Manganese),
            26 => Some(Element::Iron),
            27 => Some(Element::Cobalt),
            28 => Some(Element::Nickel),
            29 => Some(Element::Copper),
            30 => Some(Element::Zinc),
            31 => Some(Element::Gallium),
            32 => Some(Element::Germanium),
            33 => Some(Element::Arsenic),
            34 => Some(Element::Selenium),
            35 => Some(Element::Bromine),
            36 => Some(Element::Krypton),
            37 => Some(Element::Rubidium),
            38 => Some(Element::Strontium),
            39 => Some(Element::Yttrium),
            40 => Some(Element::Zirconium),
            41 => Some(Element::Niobium),
            42 => Some(Element::Molybdenum),
            43 => Some(Element::Technetium),
            44 => Some(Element::Ruthenium),
            45 => Some(Element::Rhodium),
            46 => Some(Element::Palladium),
            47 => Some(Element::Silver),
            48 => Some(Element::Cadmium),
            49 => Some(Element::Indium),
            50 => Some(Element::Tin),
            51 => Some(Element::Antimony),
            52 => Some(Element::Tellurium),
            53 => Some(Element::Iodine),
            54 => Some(Element::Xenon),
            55 => Some(Element::Caesium),
            56 => Some(Element::Barium),
            57 => Some(Element::Lanthanum),
            58 => Some(Element::Cerium),
            59 => Some(Element::Praseodymium),
            60 => Some(Element::Neodymium),
            61 => Some(Element::Promethium),
            62 => Some(Element::Samarium),
            63 => Some(Element::Europium),
            64 => Some(Element::Gadolinium),
            65 => Some(Element::Terbium),
            66 => Some(Element::Dysprosium),
            67 => Some(Element::Holmium),
            68 => Some(Element::Erbium),
            69 => Some(Element::Thulium),
            70 => Some(Element::Ytterbium),
            71 => Some(Element::Lutetium),
            72 => Some(Element::Hafnium),
            73 => Some(Element::Tantalum),
            74 => Some(Element::Tungsten),
            75 => Some(Element::Rhenium),
            76 => Some(Element::Osmium),
            77 => Some(Element::Iridium),
            78 => Some(Element::Platinum),
            79 => Some(Element::Gold),
            80 => Some(Element::Mercury),
            81 => Some(Element::Thallium),
            82 => Some(Element::Lead),
            83 => Some(Element::Bismuth),
            84 => Some(Element::Polonium),
            85 => Some(Element::Astatine),
            86 => Some(Element::Radon),
            87 => Some(Element::Francium),
            88 => Some(Element::Radium),
            89 => Some(Element::Actinium),
            90 => Some(Element::Thorium),
            91 => Some(Element::Protactinium),
            92 => Some(Element::Uranium),
            93 => Some(Element::Neptunium),
            94 => Some(Element::Plutonium),
            95 => Some(Element::Americium),
            96 => Some(Element::Curium),
            97 => Some(Element::Berkelium),
            98 => Some(Element::Californium),
            99 => Some(Element::Einsteinium),
            100 => Some(Element::Fermium),
            101 => Some(Element::Mendelevium),
            102 => Some(Element::Nobelium),
            103 => Some(Element::Lawrencium),
            104 => Some(Element::Rutherfordium),
            105 => Some(Element::Dubnium),
            106 => Some(Element::Seaborgium),
            107 => Some(Element::Bohrium),
            108 => Some(Element::Hassium),
            109 => Some(Element::Meitnerium),
            110 => Some(Element::Darmstadtium),
            111 => Some(Element::Roentgenium),
            112 => Some(Element::Copernicium),
            113 => Some(Element::Nihonium),
            114 => Some(Element::Flerovium),
            115 => Some(Element::Moscovium),
            116 => Some(Element::Livermorium),
            117 => Some(Element::Tennessine),
            118 => Some(Element::Oganesson),
            _ => None,
        }
    }

    /// Returns `Element`'s name.
    ///
    /// # Examples
    ///
    /// ```
    /// # use nkl::core::Element;
    /// assert_eq!(Element::Hydrogen.name(), "Hydrogen");
    /// ```
    pub fn name(&self) -> &str {
        match self {
            Element::Hydrogen => "Hydrogen",
            Element::Helium => "Helium",
            Element::Lithium => "Lithium",
            Element::Beryllium => "Beryllium",
            Element::Boron => "Boron",
            Element::Carbon => "Carbon",
            Element::Nitrogen => "Nitrogen",
            Element::Oxygen => "Oxygen",
            Element::Fluorine => "Fluorine",
            Element::Neon => "Neon",
            Element::Sodium => "Sodium",
            Element::Magnesium => "Magnesium",
            Element::Aluminium => "Aluminium",
            Element::Silicon => "Silicon",
            Element::Phosphorus => "Phosphorus",
            Element::Sulfur => "Sulfur",
            Element::Chlorine => "Chlorine",
            Element::Argon => "Argon",
            Element::Potassium => "Potassium",
            Element::Calcium => "Calcium",
            Element::Scandium => "Scandium",
            Element::Titanium => "Titanium",
            Element::Vanadium => "Vanadium",
            Element::Chromium => "Chromium",
            Element::Manganese => "Manganese",
            Element::Iron => "Iron",
            Element::Cobalt => "Cobalt",
            Element::Nickel => "Nickel",
            Element::Copper => "Copper",
            Element::Zinc => "Zinc",
            Element::Gallium => "Gallium",
            Element::Germanium => "Germanium",
            Element::Arsenic => "Arsenic",
            Element::Selenium => "Selenium",
            Element::Bromine => "Bromine",
            Element::Krypton => "Krypton",
            Element::Rubidium => "Rubidium",
            Element::Strontium => "Strontium",
            Element::Yttrium => "Yttrium",
            Element::Zirconium => "Zirconium",
            Element::Niobium => "Niobium",
            Element::Molybdenum => "Molybdenum",
            Element::Technetium => "Technetium",
            Element::Ruthenium => "Ruthenium",
            Element::Rhodium => "Rhodium",
            Element::Palladium => "Palladium",
            Element::Silver => "Silver",
            Element::Cadmium => "Cadmium",
            Element::Indium => "Indium",
            Element::Tin => "Tin",
            Element::Antimony => "Antimony",
            Element::Tellurium => "Tellurium",
            Element::Iodine => "Iodine",
            Element::Xenon => "Xenon",
            Element::Caesium => "Caesium",
            Element::Barium => "Barium",
            Element::Lanthanum => "Lanthanum",
            Element::Cerium => "Cerium",
            Element::Praseodymium => "Praseodymium",
            Element::Neodymium => "Neodymium",
            Element::Promethium => "Promethium",
            Element::Samarium => "Samarium",
            Element::Europium => "Europium",
            Element::Gadolinium => "Gadolinium",
            Element::Terbium => "Terbium",
            Element::Dysprosium => "Dysprosium",
            Element::Holmium => "Holmium",
            Element::Erbium => "Erbium",
            Element::Thulium => "Thulium",
            Element::Ytterbium => "Ytterbium",
            Element::Lutetium => "Lutetium",
            Element::Hafnium => "Hafnium",
            Element::Tantalum => "Tantalum",
            Element::Tungsten => "Tungsten",
            Element::Rhenium => "Rhenium",
            Element::Osmium => "Osmium",
            Element::Iridium => "Iridium",
            Element::Platinum => "Platinum",
            Element::Gold => "Gold",
            Element::Mercury => "Mercury",
            Element::Thallium => "Thallium",
            Element::Lead => "Lead",
            Element::Bismuth => "Bismuth",
            Element::Polonium => "Polonium",
            Element::Astatine => "Astatine",
            Element::Radon => "Radon",
            Element::Francium => "Francium",
            Element::Radium => "Radium",
            Element::Actinium => "Actinium",
            Element::Thorium => "Thorium",
            Element::Protactinium => "Protactinium",
            Element::Uranium => "Uranium",
            Element::Neptunium => "Neptunium",
            Element::Plutonium => "Plutonium",
            Element::Americium => "Americium",
            Element::Curium => "Curium",
            Element::Berkelium => "Berkelium",
            Element::Californium => "Californium",
            Element::Einsteinium => "Einsteinium",
            Element::Fermium => "Fermium",
            Element::Mendelevium => "Mendelevium",
            Element::Nobelium => "Nobelium",
            Element::Lawrencium => "Lawrencium",
            Element::Rutherfordium => "Rutherfordium",
            Element::Dubnium => "Dubnium",
            Element::Seaborgium => "Seaborgium",
            Element::Bohrium => "Bohrium",
            Element::Hassium => "Hassium",
            Element::Meitnerium => "Meitnerium",
            Element::Darmstadtium => "Darmstadtium",
            Element::Roentgenium => "Roentgenium",
            Element::Copernicium => "Copernicium",
            Element::Nihonium => "Nihonium",
            Element::Flerovium => "Flerovium",
            Element::Moscovium => "Moscovium",
            Element::Livermorium => "Livermorium",
            Element::Tennessine => "Tennessine",
            Element::Oganesson => "Oganesson",
        }
    }

    /// Returns `Element`'s symbol.
    ///
    /// # Examples
    ///
    /// ```
    /// # use nkl::core::Element;
    /// assert_eq!(Element::Hydrogen.symbol(), "H");
    /// ```
    pub fn symbol(&self) -> &str {
        match self {
            Element::Hydrogen => "H",
            Element::Helium => "He",
            Element::Lithium => "Li",
            Element::Beryllium => "Be",
            Element::Boron => "B",
            Element::Carbon => "C",
            Element::Nitrogen => "N",
            Element::Oxygen => "O",
            Element::Fluorine => "F",
            Element::Neon => "Ne",
            Element::Sodium => "Na",
            Element::Magnesium => "Mg",
            Element::Aluminium => "Al",
            Element::Silicon => "Si",
            Element::Phosphorus => "P",
            Element::Sulfur => "S",
            Element::Chlorine => "Cl",
            Element::Argon => "Ar",
            Element::Potassium => "K",
            Element::Calcium => "Ca",
            Element::Scandium => "Sc",
            Element::Titanium => "Ti",
            Element::Vanadium => "V",
            Element::Chromium => "Cr",
            Element::Manganese => "Mn",
            Element::Iron => "Fe",
            Element::Cobalt => "Co",
            Element::Nickel => "Ni",
            Element::Copper => "Cu",
            Element::Zinc => "Zn",
            Element::Gallium => "Ga",
            Element::Germanium => "Ge",
            Element::Arsenic => "As",
            Element::Selenium => "Se",
            Element::Bromine => "Br",
            Element::Krypton => "Kr",
            Element::Rubidium => "Rb",
            Element::Strontium => "Sr",
            Element::Yttrium => "Y",
            Element::Zirconium => "Zr",
            Element::Niobium => "Nb",
            Element::Molybdenum => "Mo",
            Element::Technetium => "Tc",
            Element::Ruthenium => "Ru",
            Element::Rhodium => "Rh",
            Element::Palladium => "Pd",
            Element::Silver => "Ag",
            Element::Cadmium => "Cd",
            Element::Indium => "In",
            Element::Tin => "Sn",
            Element::Antimony => "Sb",
            Element::Tellurium => "Te",
            Element::Iodine => "I",
            Element::Xenon => "Xe",
            Element::Caesium => "Cs",
            Element::Barium => "Ba",
            Element::Lanthanum => "La",
            Element::Cerium => "Ce",
            Element::Praseodymium => "Pr",
            Element::Neodymium => "Nd",
            Element::Promethium => "Pm",
            Element::Samarium => "Sm",
            Element::Europium => "Eu",
            Element::Gadolinium => "Gd",
            Element::Terbium => "Tb",
            Element::Dysprosium => "Dy",
            Element::Holmium => "Ho",
            Element::Erbium => "Er",
            Element::Thulium => "Tm",
            Element::Ytterbium => "Yb",
            Element::Lutetium => "Lu",
            Element::Hafnium => "Hf",
            Element::Tantalum => "Ta",
            Element::Tungsten => "W",
            Element::Rhenium => "Re",
            Element::Osmium => "Os",
            Element::Iridium => "Ir",
            Element::Platinum => "Pt",
            Element::Gold => "Au",
            Element::Mercury => "Hg",
            Element::Thallium => "Tl",
            Element::Lead => "Pb",
            Element::Bismuth => "Bi",
            Element::Polonium => "Po",
            Element::Astatine => "At",
            Element::Radon => "Rn",
            Element::Francium => "Fr",
            Element::Radium => "Ra",
            Element::Actinium => "Ac",
            Element::Thorium => "Th",
            Element::Protactinium => "Pa",
            Element::Uranium => "U",
            Element::Neptunium => "Np",
            Element::Plutonium => "Pu",
            Element::Americium => "Am",
            Element::Curium => "Cm",
            Element::Berkelium => "Bk",
            Element::Californium => "Cf",
            Element::Einsteinium => "Es",
            Element::Fermium => "Fm",
            Element::Mendelevium => "Md",
            Element::Nobelium => "No",
            Element::Lawrencium => "Lr",
            Element::Rutherfordium => "Rf",
            Element::Dubnium => "Db",
            Element::Seaborgium => "Sg",
            Element::Bohrium => "Bh",
            Element::Hassium => "Hs",
            Element::Meitnerium => "Mt",
            Element::Darmstadtium => "Ds",
            Element::Roentgenium => "Rg",
            Element::Copernicium => "Cn",
            Element::Nihonium => "Nh",
            Element::Flerovium => "Fl",
            Element::Moscovium => "Mc",
            Element::Livermorium => "Lv",
            Element::Tennessine => "Ts",
            Element::Oganesson => "Og",
        }
    }

    /// Returns `Element`'s atomic number `A`.
    ///
    /// # Examples
    ///
    /// ```
    /// # use nkl::core::Element;
    /// assert_eq!(Element::Hydrogen.atomic_number(), 1);
    /// ```
    pub fn atomic_number(&self) -> u32 {
        match self {
            Element::Hydrogen => 1,
            Element::Helium => 2,
            Element::Lithium => 3,
            Element::Beryllium => 4,
            Element::Boron => 5,
            Element::Carbon => 6,
            Element::Nitrogen => 7,
            Element::Oxygen => 8,
            Element::Fluorine => 9,
            Element::Neon => 10,
            Element::Sodium => 11,
            Element::Magnesium => 12,
            Element::Aluminium => 13,
            Element::Silicon => 14,
            Element::Phosphorus => 15,
            Element::Sulfur => 16,
            Element::Chlorine => 17,
            Element::Argon => 18,
            Element::Potassium => 19,
            Element::Calcium => 20,
            Element::Scandium => 21,
            Element::Titanium => 22,
            Element::Vanadium => 23,
            Element::Chromium => 24,
            Element::Manganese => 25,
            Element::Iron => 26,
            Element::Cobalt => 27,
            Element::Nickel => 28,
            Element::Copper => 29,
            Element::Zinc => 30,
            Element::Gallium => 31,
            Element::Germanium => 32,
            Element::Arsenic => 33,
            Element::Selenium => 34,
            Element::Bromine => 35,
            Element::Krypton => 36,
            Element::Rubidium => 37,
            Element::Strontium => 38,
            Element::Yttrium => 39,
            Element::Zirconium => 40,
            Element::Niobium => 41,
            Element::Molybdenum => 42,
            Element::Technetium => 43,
            Element::Ruthenium => 44,
            Element::Rhodium => 45,
            Element::Palladium => 46,
            Element::Silver => 47,
            Element::Cadmium => 48,
            Element::Indium => 49,
            Element::Tin => 50,
            Element::Antimony => 51,
            Element::Tellurium => 52,
            Element::Iodine => 53,
            Element::Xenon => 54,
            Element::Caesium => 55,
            Element::Barium => 56,
            Element::Lanthanum => 57,
            Element::Cerium => 58,
            Element::Praseodymium => 59,
            Element::Neodymium => 60,
            Element::Promethium => 61,
            Element::Samarium => 62,
            Element::Europium => 63,
            Element::Gadolinium => 64,
            Element::Terbium => 65,
            Element::Dysprosium => 66,
            Element::Holmium => 67,
            Element::Erbium => 68,
            Element::Thulium => 69,
            Element::Ytterbium => 70,
            Element::Lutetium => 71,
            Element::Hafnium => 72,
            Element::Tantalum => 73,
            Element::Tungsten => 74,
            Element::Rhenium => 75,
            Element::Osmium => 76,
            Element::Iridium => 77,
            Element::Platinum => 78,
            Element::Gold => 79,
            Element::Mercury => 80,
            Element::Thallium => 81,
            Element::Lead => 82,
            Element::Bismuth => 83,
            Element::Polonium => 84,
            Element::Astatine => 85,
            Element::Radon => 86,
            Element::Francium => 87,
            Element::Radium => 88,
            Element::Actinium => 89,
            Element::Thorium => 90,
            Element::Protactinium => 91,
            Element::Uranium => 92,
            Element::Neptunium => 93,
            Element::Plutonium => 94,
            Element::Americium => 95,
            Element::Curium => 96,
            Element::Berkelium => 97,
            Element::Californium => 98,
            Element::Einsteinium => 99,
            Element::Fermium => 100,
            Element::Mendelevium => 101,
            Element::Nobelium => 102,
            Element::Lawrencium => 103,
            Element::Rutherfordium => 104,
            Element::Dubnium => 105,
            Element::Seaborgium => 106,
            Element::Bohrium => 107,
            Element::Hassium => 108,
            Element::Meitnerium => 109,
            Element::Darmstadtium => 110,
            Element::Roentgenium => 111,
            Element::Copernicium => 112,
            Element::Nihonium => 113,
            Element::Flerovium => 114,
            Element::Moscovium => 115,
            Element::Livermorium => 116,
            Element::Tennessine => 117,
            Element::Oganesson => 118,
        }
    }
}
